package io.github.piscescup.fabricmc.datagen.trade;

import net.fabricmc.fabric.api.datagen.v1.FabricPackOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricDynamicRegistryProvider;
import net.minecraft.core.HolderLookup;
import net.minecraft.core.registries.Registries;
import net.minecraft.world.item.trading.TradeSet;

import java.util.concurrent.CompletableFuture;

/**
 * Emits the {@link TradeSet} entries selected by a trade data-generation model.
 *
 * <p>The registry lookup must contain the model's bootstrapped trade sets.
 * Each emitted set references a level tag generated by the trade tag provider.</p>
 *
 * @author REN YuanTong
 * @since 1.0.0
 */
public final class TradeSetRegistryGenerator
    extends FabricDynamicRegistryProvider
{

    /** Model selecting which bootstrapped trade sets are written. */
    private final VillagerTradeDatagenModel model;

    /**
     * Creates a provider for the model's trade sets.
     *
     * @param output the Fabric pack output receiving generated files
     * @param registriesFuture the future supplying the bootstrapped registry lookup
     * @param model the model whose trade-set keys should be emitted
     */
    public TradeSetRegistryGenerator(
        FabricPackOutput output,
        CompletableFuture<HolderLookup.Provider> registriesFuture,
        VillagerTradeDatagenModel model
    ) {
        super(output, registriesFuture);
        this.model = model;
    }

    /**
     * Selects the model's trade sets from the generated registry lookup.
     *
     * @param registries the registry lookup containing the bootstrapped trade sets
     * @param entries the output collection receiving the selected entries
     */
    @Override
    protected void configure(
        HolderLookup.Provider registries,
        Entries entries
    ) {
        HolderLookup.RegistryLookup<TradeSet> lookup =
            registries.lookupOrThrow(Registries.TRADE_SET);

        model.tradeSetKeys().forEach(key ->
                                         entries.add(lookup, key)
        );
    }

    /**
     * Returns the provider name used in data-generator diagnostics.
     *
     * @return {@code Villager Trade Sets}
     */
    @Override
    public String getName() {
        return "Villager Trade Sets";
    }
}
